-- USE javanos;

DROP TABLE IF EXISTS TBL_LNF;
DROP TABLE IF EXISTS TBL_COMMUNITY;
DROP TABLE IF EXISTS TBL_PIC;
DROP TABLE IF EXISTS TBL_REPORT;
DROP TABLE IF EXISTS TBL_NOTICE;
DROP TABLE IF EXISTS TBL_DOWN;
DROP TABLE IF EXISTS TBL_STATION;
DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE TBL_USER(
	USER_NO INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID VARCHAR(50) UNIQUE,
	USER_PWD VARCHAR(255) NOT NULL,
	USER_NAME VARCHAR(50) NOT NULL,
	USER_NICKNAME VARCHAR(50) NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_ROLE VARCHAR(15) DEFAULT 'ROLE_USER' CHECK(USER_ROLE IN ('ROLE_USER', 'ROLE_ADMIN')),
	USER_ENROLL_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	USER_STATUS VARCHAR(2) DEFAULT 'Y' CHECK(USER_STATUS IN ('Y', 'N')),
	USER_STOP_DATE DATETIME
); 

/* TBL_USER 테이블에 관리자 계정 추가*/
INSERT INTO TBL_USER (USER_ID, USER_PWD, USER_NAME, USER_NICKNAME, USER_EMAIL, USER_ROLE) 
VALUES ('admin', 'admin', '관리자', '관리자', 'admin@google.com', 'ROLE_ADMIN');

CREATE TABLE TBL_STATION(
	STA_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '역 번호(PK)',
    STA_CODE INT UNIQUE COMMENT '역 코드',
    STA_NAME VARCHAR(20) NOT NULL COMMENT '역명',
    STA_LINE VARCHAR(10) NOT NULL COMMENT '호선'
);

CREATE TABLE TBL_LNF(
	LNF_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '게시판 번호(PK)',
	LNF_MISSING VARCHAR(100) NOT NULL COMMENT '분실 품목',
	LNF_FIND_DATE DATE DEFAULT (CURRENT_DATE) NOT NULL COMMENT '발견일',
	LNF_FIND_TIME TIME DEFAULT (CURRENT_TIME) COMMENT '발견 시간',
	LNF_KEEP VARCHAR(100) NOT NULL COMMENT '보관 장소',
	LNF_DESCRIPTION VARCHAR(4000) COMMENT '내용',
	LNF_ENROLL_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '작성일',
	LNF_MODIFY_DATE DATETIME DEFAULT NULL COMMENT '수정일',
	LNF_BOARD_STATUS VARCHAR(2) DEFAULT 'Y' CHECK(LNF_BOARD_STATUS IN ('Y', 'N')) NOT NULL COMMENT '게시판 상태',
	LNF_WRITER_NO INT NOT NULL COMMENT '회원 번호(FK)',
	LNF_STA_NO INT NOT NULL COMMENT '역 번호(FK)',
	FOREIGN KEY (LNF_WRITER_NO) REFERENCES TBL_USER (USER_NO),
	FOREIGN KEY (LNF_STA_NO) REFERENCES TBL_STATION (STA_NO)
);

CREATE TABLE TBL_COMMUNITY (
    COMMUNITY_NO INT AUTO_INCREMENT PRIMARY KEY,
    COMMUNITY_TITLE VARCHAR(255) NOT NULL,
    COMMUNITY_BODY VARCHAR(255) NOT NULL,
    COMMUNITY_COUNT INT DEFAULT 0,
    COMMUNITY_ENROLL_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMMUNITY_MODIFY_DATE DATETIME,
    COMMUNITY_BOARD_STATUS VARCHAR(2) DEFAULT 'Y' NOT NULL,
    USER_NO INT NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO)
);

CREATE TABLE TBL_PIC (
    PIC_NO INT AUTO_INCREMENT PRIMARY KEY,
    SAVED_NAME VARCHAR(255) NOT NULL,
    SAVE_PATH VARCHAR(255) NOT NULL,
    FILE_TYPE VARCHAR(5) CHECK(FILE_TYPE IN ('TITLE', 'BODY')) NOT NULL,
	THUMBNAIL_PATH VARCHAR(255) NOT NULL,
	PIC_BOARD_STATUS VARCHAR(1) DEFAULT 'Y',
    COMMUNITY_NO INT NOT NULL,
    FOREIGN KEY (COMMUNITY_NO) REFERENCES TBL_COMMUNITY (COMMUNITY_NO)
);

CREATE TABLE TBL_REPORT (
    REPORT_NO INT AUTO_INCREMENT PRIMARY KEY,
    REPORT_REASON VARCHAR(255),
    REPORT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    REPORT_STATUS VARCHAR(3) DEFAULT 'Y' CHECK(REPORT_STATUS IN ('Y', 'N')),
    REPORT_USER_NO INT,
    REPORTED_USER_NO INT,
    PIC_NO INT,
    FOREIGN KEY (REPORT_USER_NO) REFERENCES TBL_USER (USER_NO),
    FOREIGN KEY (REPORTED_USER_NO) REFERENCES TBL_USER (USER_NO),
    FOREIGN KEY (PIC_NO) REFERENCES TBL_PIC (PIC_NO)
);

CREATE TABLE TBL_NOTICE (
	NOTICE_NO INT AUTO_INCREMENT PRIMARY KEY,
	NOTICE_TITLE VARCHAR(100) NOT NULL,
	NOTICE_BODY VARCHAR(4000) NOT NULL,
	NOTICE_ENROLL_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	NOTICE_MODIFY_DATE DATETIME,
	NOTICE_COUNT INT DEFAULT 0,
	NOTICE_BOARD_STATUS VARCHAR(2) DEFAULT 'Y',
	NOTICE_USER_NO INT NOT NULL,
	FOREIGN KEY (NOTICE_USER_NO) REFERENCES TBL_USER (USER_NO)
);

CREATE TABLE TBL_DOWN(
	DOWN_NO INT AUTO_INCREMENT PRIMARY KEY,
	DOWN_ROOM  VARCHAR(20) NOT NULL,
	DOWN_FULL VARCHAR(15) NOT NULL,
	DOWN_ENROLL_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	DOWN_MODIFY_DATE DATETIME,
	DOWN_BOARD_STATUS VARCHAR(2) DEFAULT 'Y' CHECK(DOWN_BOARD_STATUS IN ('Y', 'N')),
	DOWN_USER_NO INT,
	DOWN_STA_NO INT,
	IN_STA_NO INT,
	FOREIGN KEY (DOWN_USER_NO) REFERENCES TBL_USER (USER_NO),
	FOREIGN KEY (DOWN_STA_NO) REFERENCES TBL_STATION (STA_NO),
	FOREIGN KEY (IN_STA_NO) REFERENCES TBL_STATION (STA_NO) 
);



-- TBL_USER 테이블에 데이터 삽입
INSERT INTO TBL_USER (USER_ID, USER_PWD, USER_NAME, USER_NICKNAME, USER_EMAIL) 
VALUES ('user01', 'user01', '사용자1', '사용자1', 'user01@google.com');
INSERT INTO TBL_USER (USER_ID, USER_PWD, USER_NAME, USER_NICKNAME, USER_EMAIL) 
VALUES ('user02', 'user02', '사용자2', '사용자2', 'user02@google.com');

-- TBL_STATION 테이블에 데이터 삽입 
INSERT INTO TBL_STATION (STA_CODE, STA_NAME, STA_LINE) VALUES
(340, '가락시장', '3호선'),
(2548, '천호', '5호선');

-- TBL_LNF 테이블에 데이터 삽입
INSERT INTO TBL_LNF (LNF_MISSING, LNF_FIND_DATE, LNF_FIND_TIME, LNF_KEEP, LNF_DESCRIPTION, LNF_WRITER_NO, LNF_STA_NO) VALUES 
('냉장고', '2024-06-20', '12:30:00', '가락시장역 3호선 역사', '냉장고를 어떻게 가지고 다니시죠?', 1, 1),
('지갑', '2024-06-21', '10:15:00', '발견 장소', '저 민증 3개 있어요. 잃어버려서 재발급 2번 했어요. 근데 집에서 다시 찾았어요.', 1, 2);

--- TBL_COMMUNITY 테이블에 데이터 삽입
INSERT INTO TBL_COMMUNITY(COMMUNITY_TITLE,COMMUNITY_BODY,USER_NO) VALUES("제목1","내용1",2);
INSERT INTO TBL_COMMUNITY(COMMUNITY_TITLE,COMMUNITY_BODY,USER_NO) VALUES("제목2","내용2",2);

INSERT INTO TBL_COMMUNITY(COMMUNITY_TITLE,COMMUNITY_BODY,USER_NO) VALUES("사진있는 게시글 제목3","사진 있는 게시글 내용3",3);
INSERT INTO TBL_PIC(SAVED_NAME,SAVE_PATH,FILE_TYPE,THUMBNAIL_PATH,COMMUNITY_NO) VALUES("사진 저장되는 이름","로컬에 저장되는 주소","TITLE","서버에 저장되는 주소",3);

INSERT INTO TBL_COMMUNITY(COMMUNITY_TITLE,COMMUNITY_BODY,USER_NO) VALUES("사진있는 게시글 제목4","사진 있는 게시글 내용4",2);
INSERT INTO TBL_PIC(SAVED_NAME,SAVE_PATH,FILE_TYPE,THUMBNAIL_PATH,COMMUNITY_NO) VALUES("사진 저장되는 이름","로컬에 저장되는 주소","TITLE","서버에 저장되는 주소",3);
INSERT INTO TBL_PIC(SAVED_NAME,SAVE_PATH,FILE_TYPE,THUMBNAIL_PATH,COMMUNITY_NO) VALUES("사진 저장되는 이름","로컬에 저장되는 주소","BODY","서버에 저장되는 주소",3);
INSERT INTO TBL_PIC(SAVED_NAME,SAVE_PATH,FILE_TYPE,THUMBNAIL_PATH,COMMUNITY_NO) VALUES("사진 저장되는 이름","로컬에 저장되는 주소","BODY","서버에 저장되는 주소",3);

-- TBL_REPORT 테이블에 데이터 삽입
INSERT INTO TBL_REPORT (REPORT_REASON, REPORT_DATE, REPORT_STATUS, REPORT_USER_NO, REPORTED_USER_NO, PIC_NO)
VALUES ('모욕적인 글 작성', CURRENT_TIMESTAMP, 'Y', 1, 2, 2);

-- TBL_NOTICE 테이블에 데이터 삽입
INSERT INTO TBL_NOTICE(NOTICE_NO, NOTICE_TITLE, NOTICE_BODY, NOTICE_ENROLL_DATE, NOTICE_MODIFY_DATE, NOTICE_COUNT, NOTICE_BOARD_STATUS, NOTICE_USER_NO)
VALUES (1, '첫 공지', '첫번째 공지글 입니다.', CURRENT_TIMESTAMP, NULL, DEFAULT, 'Y', 1);


-- TBL_DOWN 테이블에 데이터 삽입
INSERT INTO TBL_DOWN (DOWN_ROOM , DOWN_FULL, DOWN_USER_NO, DOWN_STA_NO, IN_STA_NO)
VALUES ('2-1칸', '상', 1,1,1);

INSERT INTO TBL_DOWN (DOWN_ROOM , DOWN_FULL, DOWN_USER_NO, DOWN_STA_NO, IN_STA_NO)
VALUES ('3-2칸', '중', 1,2,2);
